# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstaCloneFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstaCloneFirebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  # pod 'SDWebImageSwiftUI'
pod 'SDWebImage', '~> 5.0'  
pod 'OneSignal', '>= 2.11.2', '< 3.0'

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.11.2', '< 3.0'

end

end

